#!/usr/bin/env bash
# shellcheck disable=SC2006
# Get information about a subdomain of a domain

function subdomain_info() {
    dig_result=$(dig $2.$1)
    info=$(echo "$dig_result" | awk '/ANSWER SECTION:/ {getline; print $4, $5}')
    echo "${info[@]}"
}

function final_message() {
    echo "The subdomain $1 is a $2 record and points to $3"
}

domain=$1
subdomain=$2

if [[ $subdomain ]]; then
    subdomains=("$subdomain")
else
    subdomains=('www' 'lb-01' 'web-01' 'web-02')
fi
for sub in "${subdomains[@]}"; do
    info=$(subdomain_info "$domain" "$sub")
    info=($info)
    message=$(final_message "$sub" "${info[0]}" "${info[1]}")
    echo "$message"
done
