#!/usr/bin/env bash
# Install nginx, edit the 404 and defauld webpage and add custom headers
sudo apt update
sudo apt -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "0,/}/s/}/}\n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}/" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/error404.html

sed -i "0,/server {/s/server {/server {\n\terror_page 404 \/error404.html;/" /etc/nginx/sites-available/default

# Add a custom header "X-Served_By"
sed -i "/server {/a\        X-Served-By \$hostname;" /etc/nginx/sites-available/default

service nginx start
