#!/usr/bin/env bash
# Install an Nginx server and edit the default webpage
sudo apt update
sudo apt -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "0,/}/s/}/}\n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sed -i "0,/server {/s/server {/server {\n\terror_page 404 \/error404.html;/" /etc/nginx/sites-available/default
service nginx start 
