#!/usr/bin/env bash
# Print To infinity and beyond indefinitely and
# display Y U no love me?! whe recieving a SIGINT 
# and display I hate the kill command when receiving a SIGTERM signal
# , delte the /var/run/myscript.pid that created it first when either 
# SIGQUIT or SIGTERM

echo "$$" > /var/run/myscript.pid

trap "echo 'I hate the kill command' &&
	rm /var/run/myscript.pid && 
	exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/myscript.pid && exit" SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 2
done


