#!/usr/bin/env bash
# Parse each line in  etc/passwd and make a store of thhem:
# Format: 
#	The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO


while IFS=: read -r username password u_id g_id info home shell; do
	echo "The user $username is part of the $g_id gang, lives in $home and rides $shell. $u_id's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
