#!/usr/bin/env bash
# Make nginx listen to a specifc portna dn make it run 
# with specific user
sed -i 's/^user .*;/user nginx nginx;/g' /etc/nginx/nginx.conf
sed -i 's/^listen  .*;/listen 8080;/g' /etc/nginx/sites-available/default
nginx -s reload

