#!/usr/bin/env bash
# Make nginx listen to a specifc portna dn make it run 
# And change the user
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/#user .*;/user nginx;/' /etc/nginx/nginx.conf
service nginx restart
